
server:
  port: 8080
spring:
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/library'
    username: 'user'
    password: 'password'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    admin:
      enabled: true
      jmx-name: org.springframework.boot:type=Admin,name=SpringApplication

#  application.admin.enabled=true
#  application.admin.jmx-name=org.springframework.boot:type=Admin,name=SpringApplication # JMX name of the application admin MBean.
#logging:
#  level:
#    org.springframework: DEBUG
