spring:
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true
  datasource:
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: 'postgres'
    password: 'postgres'
  jpa:
    hibernate:
      ddl-auto: validate

